INSERT into resources (owner_id, title, description, cover_image_url, external_url)
VALUES (1, 'vestibulum sed arcu non odio euismod lacinia at quis risus', 'morbi quis commodo odio aenean sed adipiscing diam donec adipiscing', 'https://cdn-bdfbc.nitrocdn.com/mpQHUpeCagYMmyclYzWrEuJOvwEOajTJ/assets/static/optimized/rev-33edbce/wp-content/uploads/2022/12/cover7-1080x675.jpg', 'https://www.google.com/'),
(2, 'donec ultrices tincidunt arcu non sodales neque sodales ut etiam', 'sagittis vitae et leo duis ut diam quam nulla porttitor', 'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg', 'https://www.amazon.ca/'),
(3, 'purus sit amet luctus venenatis lectus magna fringilla urna porttitor', 'ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_655998316_2000149920009280207_354374.jpg', 'https://www.reddit.com/'),
(4, 'id nibh tortor id aliquet lectus proin nibh nisl condimentum', 'metus dictum at tempor commodo ullamcorper a lacus vestibulum sed', 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'https://www.youtube.com/'),
(10, 'purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae', 'neque volutpat ac tincidunt vitae semper quis lectus nulla at', 'https://cdn-bdfbc.nitrocdn.com/mpQHUpeCagYMmyclYzWrEuJOvwEOajTJ/assets/static/optimized/rev-33edbce/wp-content/uploads/2022/12/cover7-1080x675.jpg', 'https://discord.com/'),
(12, 'felis eget nunc lobortis mattis aliquam faucibus purus in massa', 'lectus urna duis convallis convallis tellus id interdum velit laoreet', 'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg' ,'https://slack.com/'),
(9, 'phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim', 'vivamus arcu felis bibendum ut tristique et egestas quis ipsum', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_655998316_2000149920009280207_354374.jpg', 'https://www.microsoft.com/en-ca'),
(7, 'imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis', 'erat velit scelerisque in dictum non consectetur a erat nam', 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'https://www.reddit.com/'),
(1, 'non diam phasellus vestibulum lorem sed risus ultricies tristique nulla', 'quis enim lobortis scelerisque fermentum dui faucibus in ornare quam', 'https://cdn-bdfbc.nitrocdn.com/mpQHUpeCagYMmyclYzWrEuJOvwEOajTJ/assets/static/optimized/rev-33edbce/wp-content/uploads/2022/12/cover7-1080x675.jpg', 'https://www.reddit.com/'),
(1, 'id leo in vitae turpis massa sed elementum tempus egestas', 'dui faucibus in ornare quam viverra orci sagittis eu volutpat', 'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg', 'https://www.youtube.com/'),
(13, 'commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec', 'quis vel eros donec ac odio tempor orci dapibus ultrices', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_655998316_2000149920009280207_354374.jpg', 'https://www.youtube.com/'),
(12, 'mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus', 'gravida neque convallis a cras semper auctor neque vitae tempus', 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','https://www.amazon.ca/'),
(10, 'massa id neque aliquam vestibulum morbi blandit cursus risus at', 'pharetra magna ac placerat vestibulum lectus mauris ultrices eros in', 'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg', 'https://www.amazon.ca/'),
(9, 'risus pretium quam vulputate dignissim suspendisse in est ante in', 'massa placerat duis ultricies lacus sed turpis tincidunt id aliquet', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_655998316_2000149920009280207_354374.jpg', 'https://www.ebay.ca/'),
(7, 'felis donec et odio pellentesque diam volutpat commodo sed egestas', 'sem et tortor consequat id porta nibh venenatis cras sed', 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'https://www.ebay.ca/'),
(9, 'felis donec et odio pellentesque diam volutpat commodo sed egestas', 'sit amet facilisis magna etiam tempor orci eu lobortis elementum', 'https://cdn-bdfbc.nitrocdn.com/mpQHUpeCagYMmyclYzWrEuJOvwEOajTJ/assets/static/optimized/rev-33edbce/wp-content/uploads/2022/12/cover7-1080x675.jpg', 'https://github.com/'),
(11, 'maecenas accumsan lacus vel facilisis volutpat est velit egestas dui', 'risus nec feugiat in fermentum posuere urna nec tincidunt praesent', 'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg', 'https://github.com/'),
(12, 'tincidunt id aliquet risus feugiat in ante metus dictum at', 'curabitur vitae nunc sed velit dignissim sodales ut eu sem.', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_655998316_2000149920009280207_354374.jpg', 'https://github.com/'),
(14, 'adipiscing elit pellentesque habitant morbi tristique senectus et netus et', 'aliquam ultrices sagittis orci a scelerisque purus semper eget duis', 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'https://github.com/');

INSERT into tags (resource_id, topic)
VALUES (1, 'programming'),
(1, 'coding'),
(2, 'fun'),
(2, 'crazy'),
(3, 'study'),
(3, 'education'),
(3, 'school'),
(3, 'learning'),
(4, 'food'),
(5, 'travel'),
(5, 'stars'),
(6, 'track'),
(6, 'throwing'),
(7, 'fitness'),
(7, 'volleyball'),
(8, 'sports'),
(9, 'science'),
(10, 'history'),
(11, 'strategy'),
(9, 'games'),
(5, 'games'),
(2, 'coding'),
(10, 'school'),
(11, 'university'),
(5, 'resumes');

INSERT into favourites (resource_id, user_id, liked)
VALUES (1 , 3, true),
(1, 5, true),
(2, 1, true),
(2, 3, true),
(2, 6, true),
(3, 1, true),
(3, 4, true),
(4, 1, true),
(10, 5, true),
(11, 9, true),
(12, 10, true),
(14, 9, true),
(16, 6, true),
(12, 7, true),
(9, 8, true);

INSERT into ratings (resource_id, user_id, rating)
VALUES (1, 3, 5),
(1, 2, 3),
(2, 1, 4),
(3, 6, 1),
(4, 5, 2),
(11, 2, 3),
(15, 6, 4),
(9, 5, 1),
(12, 15, 2),
(1, 16, 3),
(11, 15, 4),
(9, 12, 1),
(10, 4, 2),
(6, 5, 3),
(7, 9, 4),
(9, 6, 1),
(8, 7, 2);

INSERT into comments (resource_id, user_id, message)
VALUES (1, 2, 'wow'),
(2, 5, 'amazing'),
(3, 1, 'really informative'),
(4, 6, 'this content sucks man'),
(5, 8, 'they talk really good!'),
(6, 11, 'i did not understand'),
(7, 13, 'really helpful'),
(8, 15, 'this content could be better'),
(9, 2, 'blurry video'),
(10, 11, 'the link does not work'),
(5, 10, 'i wish the content could be better'),
(6, 9, 'boring'),
(7, 9, 'the teacher is passionate!'),
(8, 12, 'they talk to slow'),
(9, 6, 'really long but useful information'),
(10, 7, 'this content could be useful');
