DROP TABLE IF EXISTS resource CASCADE;
CREATE TABLE resource (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER NOT NULL REFERENCES user(id) DELETE ON CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  created_date DATETIME NOT NULL DEFAULT NOW(),
  cover_image_url TEXT
);

DROP TABLE IF EXISTS tag CASCADE;
CREATE TABLE tag (
  id SERIAL PRIMARY KEY NOT NULL,
  resource_id INTEGER NOT NULL REFERENCES resource(id) DELETE ON CASCADE
  topic VARCHAR(255) NOT NULL
)

DROP TABLE IF EXISTS favourite CASCADE;
CREATE TABLE favourite (
  id SERIAL PRIMARY KEY NOT NULL,
  resource_id INTEGER NOT NULL REFERENCES resource(id) DELETE ON CASCADE,
  user_id INTEGER NOT NULL REFERENCES user(id) DELETE ON CASCADE,
  liked BOOLEAN NOT NULL DEFAULT 0
)

DROP TABLE IF EXISTS rating CASCADE;
CREATE TABLE favourite (
  id SERIAL PRIMARY KEY NOT NULL,
  resource_id INTEGER NOT NULL REFERENCES resource(id) DELETE ON CASCADE,
  user_id INTEGER NOT NULL REFERENCES user(id) DELETE ON CASCADE,
  rating SMALLINT
)

DROP TABLE IF EXISTS comment CASCADE;
CREATE TABLE comment (
  id SERIAL PRIMARY KEY NOT NULL,
  resource_id INTEGER NOT NULL REFERENCES resource(id) DELETE ON CASCADE,
  user_id INTEGER NOT NULL REFERENCES user(id) DELETE ON CASCADE,
  message TEXT
)